### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Viky Cham",
  "email": "",
  "address": "123 hello world",
  "dateOfBirth": "1999-03-11",
  "registeredDate": "2026-02-11"
}

###